export const UPDATE_SELECTEDINDEX = "update_selectedIndex"
export const GET_SUPPORTAREA = "get_support_area"
export const SET_CURRENTCITY = "set_current_city" //设置当前城市
export const GET_FOOD_LIST = 'get_food_list' //获取当前城市的商品列表
export const DECREMENT_FOOD = "decrement_food" //加入食物到购物车
export const INCREMENT_FOOD = "increment_food" //去除食物到购物车
export const REMOVE_FOOD = "remove_food" //移除购物车中取消选中的食物
export const RECOVER_FOOD = "recover_food" //向购物车中添加取消选中的食物
export const UPDATE_ADDRESS_INFO ="update_address_info" //更新收获地址
export const DEL_ADDRESSITEM = "del_addressitem" //删除地址
export const ADD_ADDRESS = "add_address" //添加新地址
